project_id = "miwbbdhfbpmcrfbpulkj"

[functions.enviar-email]
verify_jwt = false

[functions.create-admin]
verify_jwt = false

[functions.sla-16-dias-alerta]
verify_jwt = false

[functions.teste-webhook-criacao]
verify_jwt = false
